services:
  openscanproxy:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "28080:8080"
      - "29090:9090"
    volumes:
      - ../configs:/app/configs
      - ../logs:/app/logs
      - ../certs:/app/certs
    restart: unless-stopped
